CREATE TABLE IF NOT EXISTS pv(
  id SERIAL PRIMARY KEY,
  name VARCHAR(512) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name)
);

ALTER TABLE config_pv ADD pv_id INTEGER REFERENCES pv(id);
ALTER TABLE config_pv ADD readback_pv_id INTEGER REFERENCES pv(id);
