services:
  alarmlogger:
    image: ghcr.io/controlsystemstudio/phoebus/service-alarm-logger:master
    ports:
      - "8080:8080"
    command: >
      /bin/bash -c "
      java -jar /alarmlogger/service-alarm-logger-*.jar -bootstrap.servers ${KAFKA_HOST_IP_ADDRESS}:9092 -es_host ${ELASTIC_HOST_IP_ADDRESS} -topics ${ALARM_TOPICS} -noshell"


