[workspace]
authors = ["milenaschedle <milena.schedle@ess.eu>"]
channels = ["conda-forge"]
name = "phoebus"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.6,<3.15"
