# Configurable user names and passwords for the inMemory authentication

demo.user=user
demo.user.password=userPass
demo.admin=admin
demo.admin.password=adminPass
demo.readOnly=johndoe
demo.readOnlyPassword=1234
