services:
  alarmserver:
    image: ghcr.io/controlsystemstudio/phoebus/service-alarm-server:csstudio-2989
    volumes:
      - /home:/home
    command: >
      /bin/bash -c "
      java -jar /alarmserver/service-alarm-server-*.jar -config ${CONFIG} -import ${CONFIG_FILE} -server ${KAFKA_HOST}:9092"
  
