CREATE TABLE IF NOT EXISTS pv(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(512) UNIQUE NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE config_pv ADD pv_id INTEGER REFERENCES pv(id);
ALTER TABLE config_pv ADD readback_pv_id INTEGER REFERENCES pv(id);

