CREATE TABLE tag (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  snapshot_id VARCHAR(100) NOT NULL REFERENCES node(unique_id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  comment VARCHAR(1000),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  username VARCHAR(30)
);
