#!/bin/bash

# External dependencies
LIB=`echo ../../dependencies/phoebus-target/target/lib/bcpkix-*.jar`
LIB+=':'`echo ../../dependencies/phoebus-target/target/lib/bcprov-*.jar`
LIB+=':'`echo ../../dependencies/phoebus-target/target/lib/bcutil-*.jar`

JAR=`echo target/core-pva*.jar`
if [ -r "$JAR" ]
then
    # Use jar
    java -cp $LIB:$JAR org.epics.pva.server.ServerDemo "$@"
else
    # Use IDE build output
    java -cp $LIB:target/classes org.epics.pva.server.ServerDemo "$@"
fi

