name: UI test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ui-test:
    uses: ./.github/workflows/_test.yml
    with:
      name: ui-test
      run: xvfb-run -a mvn --batch-mode --fail-at-end verify -P ui-tests
      report-path: '**/target/failsafe-reports/**'
      maven-opts: >-
        -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true
        -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500
