name: Unit test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    - name: Set up Java
      uses: ./.github/actions/setup-java
    - name: Unit test
      run: mvn --batch-mode --fail-at-end verify
    - name: Upload test reports
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      if: always()
      with:
        name: unit-test-reports
        path: '**/target/surefire-reports/**'
        if-no-files-found: ignore
