name: Unit test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Java
      uses: ./.github/actions/setup-java
    - name: Unit test
      run: mvn --batch-mode --fail-at-end verify
    - name: Upload test reports
      uses: actions/upload-artifact@v7
      if: always()
      with:
        name: unit-test-reports
        path: '**/target/surefire-reports/**'
        if-no-files-found: ignore
