name: Alarm Server Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths: services/alarm-server/**
    tags:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/service-alarm-server

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Maven and Java Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: '17'
          maven-version: '3.9.6'
      - name: Build
        run: mvn --batch-mode install -DskipTests
  build-and-push-image:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: Login to the registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract meta-data for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
    - name: Build and publish the Docker image
      uses: docker/build-push-action@v5
      with: 
        context: services/alarm-server
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
