name: Branch

on:
  push:
    branches-ignore:
      - master

permissions:
  contents: read

concurrency:
  group: branch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build.yml
