name: Phoebus build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu-latest", "windows-latest", "macos-latest"]
  
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Build
      run: mvn --batch-mode install -DskipTests

    - name: Archive build artifacts 
      uses: actions/upload-artifact@v3
      with:
        name: Phoebus product ${{ matrix.os }}
        path: |
          ${{ github.workspace }}/phoebus-product/target/*.tar.gz 
          ${{ github.workspace }}/phoebus-product/target/*.zip
