name: Release

on:
  push:
    tags:
      - '**'

permissions:
  contents: read

jobs:
  docker-image:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        service: [alarm-server, alarm-logger, save-and-restore, scan-server]
    uses: ./.github/workflows/_docker-image.yml
    with:
      image-suffix: service-${{ matrix.service }}
      context: services/${{ matrix.service }}
      maven-args: ${{ matrix.service == 'scan-server' && '-Pexecutable-jar --update-snapshots package' || '--update-snapshots package' }}
